apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Meowney-pvc
  namespace: Meowney
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
